ktor:
  deployment:
    host: "$PROD_HOST"
    port: "$PROD_PORT"
    baseUrl: "$BASE_URL"

  security:
    jwt:
      secret: "$JWT_SECRET"
      issuer: ""
      audience: ""
      realm: ""

  database:
    jdbcUrl: "$DB_DRIVER_CLASS_NAME"
    host: "$DB_HOST"
    port: "$DATABASE_PORT"
    username: "$DB_USERNAME"
    password: "$DB_PASSWORD"
    databaseName: "$DB_NAME"

  smtp:
    host: "$SMTP_HOST"
    port: "$SMTP_PORT"
    username: "$SMTP_USERNAME"
    password: "$SMTP_PASSWORD"
    fromEmail: "$SMTP_FROM_EMAIL"
    ssl: "$SMTP_SSL"
    starttls: "$SMTP_STARTTLS"