ktor:
  deployment:
    host: "$PROD_HOST:0.0.0.0"
    port: "$PROD_PORT:8080"
    baseUrl: "$BASE_URL:http://localhost:8080"

  security:
    jwt:
      secret: "$JWT_SECRETE:devSecreteKey"
      issuer: ""
      audience: ""
      realm: ""

  database:
    jdbcUrl: "$DB_DRIVER_CLASS_NAME:org.postgresql.Driver"
    host: "$DB_HOST:localhost"
    port: "$DATABASE_PORT:5432"
    username: "$DB_USERNAME:postgres"
    password: "$DB_PASSWORD:root"
    databaseName: "$DB_NAME:smartattendance"

  smtp:
    host: "$SMTP_HOST:smtp.gmail.com"
    port: "$SMTP_PORT:587"
    username: "$SMTP_USERNAME:your-email@gmail.com"
    password: "$SMTP_PASSWORD:your-app-specific-password"
    fromEmail: "$SMTP_FROM_EMAIL:your-email@gmail.com"
    ssl: "$SMTP_SSL:true"
    starttls: "$SMTP_STARTTLS:true"
